### ISSUE TITLE
Add Max-Height for Portrait Images 

### ISSUE THREAD

**Issue by Kcaden20** [Kcaden20/critical-code-cookbook#11]
Need to add a max height to avoid extremely long images when a portrait image is added
<img width="1352" alt="Screen Shot 2022-06-21 at 5 17 55 PM" src="https://user-images.githubusercontent.com/13590895/174899015-b94c90aa-2cf4-49db-ba12-43bc14e0c3f2.png">
.

**Comment by Kcaden20** [comment]
@xinemata I've added the ability to set a `proportion` to images both in regular fields and in `blocks`. 

It will always default to landscape which is just the standard styling but can be set to `square` or `portrait` to better contain larger images. See the screenshot below. 
![Screen Shot 2022-06-24 at 1 08 15 PM](https://user-images.githubusercontent.com/13590895/175609787-b480aabd-281d-404c-8900-2ced9a4bb3be.png)

**Comment by xinemata** [comment]
This worked really well & I didn't find any bugs. Closing the issue.
