### ISSUE TITLE
reducing content displayed on contribution thumbnails

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#13]
After populating the [contributions page](https://criticalcode.recipes/contributions) with content, the level of detail displayed under individual thumbnail starts to feel a little overwhelming to me. I wonder if we should simplify it by only displaying Title, Author Name, and Keywords. I'm also wondering if it's possible to add "#" in front of keywords. 

Here's an example:
<img width="278" alt="Screen Shot 2022-06-22 at 12 56 09 AM" src="https://user-images.githubusercontent.com/9159424/174964665-f12de143-a04c-4006-a197-8b6abbd166f3.png">

**Comment by Kcaden20** [comment]
@xinemata see issue: https://github.com/Kcaden20/critical-code-cookbook/issues/8

**Comment by Kcaden20** [comment]
@xinemata closed #8 and going to use this issue post as the main spot. Adding details from the previous issue below.

***

Going to add a limit on the amount of tags that show on the Contribution Hub (probably to two) to avoid stuff like this. Potentially also limiting the character count. 
Also changing the styling to look more like the tags on the contribution page (i.e with a #)
<img width="380" alt="Screen Shot 2022-06-21 at 5 11 02 PM" src="https://user-images.githubusercontent.com/13590895/174898064-f5d375cd-ddcc-40b1-aafc-db3e6e2c2d01.png">

**Comment by xinemata** [comment]
Oh yes! Sorry to have missed that and thanks for consolidating. 

For the number of tags that shows up on thumbnails: can we keep it at 3 since that's the number we've asked from the contributors?

**Comment by Kcaden20** [comment]
I've limited the categories to three as well as shortened the length of the byline. I think getting rid of it would make all the entries too same looking. It's now only `100` characters instead of `140`. 
![Screen Shot 2022-06-24 at 1 40 34 PM](https://user-images.githubusercontent.com/13590895/175614140-f0e4929c-9e58-4ae6-889e-9cc6289c560a.png)

**Comment by xinemata** [comment]
That makes sense to me. Would it be possible to align all the `<h5>` so that the entry title share the same height position?

**Comment by xinemata** [comment]
Another issue that came up for me is when the byline would start with an image caption of the entry. Would it be possible to exclude image captions from the byline?

<img width="318" alt="Screen Shot 2022-06-26 at 1 33 03 PM" src="https://user-images.githubusercontent.com/9159424/175830871-deff0e31-0ce6-4de4-84d9-6a6b92dd583c.png">

**Comment by Kcaden20** [comment]
> That makes sense to me. Would it be possible to align all the `<h5>` so that the entry title share the same height position?

Align in which way? on the same line? I don't think this is possible given how long some of the category tags are for some of the entries. The only other surefire way to make sure that they're all the same height would be to make each category tag one line.

**Comment by Kcaden20** [comment]
Figcaptions Removed! 
![Screen Shot 2022-06-27 at 12 37 19 PM](https://user-images.githubusercontent.com/13590895/175991448-e0abc53a-922d-48cf-a3be-2324fcb44f28.png)

**Comment by xinemata** [comment]
It seems like the thumbnails paddings have been adjusted in ways that make this look better to my eyes right now. I'd consider this issue closed.
