### ISSUE TITLE
Changing Section Titles & Order

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#14]
Under contribution pages:

- [x] Rename "Abstract" to "Introduction"
- [x] Rename "Body" to "The Recipe". This will also lead to naming the sub-nav.
- [x] Rename "Context" to "Q&A"
- [x] Move all "Q&A" sections to the end of the stack if possible. I'm hoping that this will make the recipes feel more inviting & less overwhelming to jump into. [Here's a mock example](https://criticalcode.recipes/contributions/jingle-tales#body).

**Comment by Kcaden20** [comment]
Updated. Q&A is after all page-specific content. 
![Screen Shot 2022-06-24 at 2 21 31 PM](https://user-images.githubusercontent.com/13590895/175632711-71fb78df-3381-44b6-95cd-2590d36dda79.png)

**Comment by xinemata** [comment]
Looks awesome. I think this flows much better now. Closing the issue.
