### ISSUE TITLE
Create stand out texts for contribution paragraphs?

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#17]
Since the contributions are pretty text-heavy, I'm wondering what you think about creating a paragraph class that would be styled as the "stand out text" to provide some visual breaks. 

It doesn't have to look like this at all, but I've made a quick draft to illustrate what I mean:

<img width="1058" alt="Screen Shot 2022-06-22 at 5 04 27 PM" src="https://user-images.githubusercontent.com/9159424/175169424-279dcd94-62bd-43b6-9a77-a0dc195461cb.png">

**Comment by Kcaden20** [comment]
Will look into the following:

- if there’s a way to add a class in kirby text to a paragraph
- if not, if there’s a markdown styling that we’re not using that can be
repurposed for this

**Comment by Kcaden20** [comment]
Might involve making a kirbyTag:
https://getkirby.com/docs/guide/content/text-formatting#kirbytext

**Comment by Kcaden20** [comment]
This has been implemented. You can now wrap text in a `(callout:...)` tag. See implementation examples below. 
![Screen Shot 2022-06-23 at 5 03 17 PM](https://user-images.githubusercontent.com/13590895/175400348-c7e092e5-5187-4f65-a5a1-9df909614421.png)
![Screen Shot 2022-06-23 at 5 03 08 PM](https://user-images.githubusercontent.com/13590895/175400351-df617953-0acf-43d9-87b0-6bab1007ef7f.png)
![Screen Shot 2022-06-23 at 5 03 01 PM](https://user-images.githubusercontent.com/13590895/175400352-b3e85f69-5095-4e1e-b907-56201589e6fa.png)

**Comment by xinemata** [comment]
Looks great, thank you!
