### ISSUE TITLE
Prev/Next Button Looks Bad on Mobile 

### ISSUE THREAD

**Issue by Kcaden20** [Kcaden20/critical-code-cookbook#2]
The text should be centered inside the button. Potentially moved to the next line? 
![IMG_1401](https://user-images.githubusercontent.com/13590895/174685033-d6e66589-2dba-41b6-9e11-5e55bdd28bb6.PNG)

**Comment by Kcaden20** [comment]
These have been centered and given their own lines.
![Screen Shot 2022-06-24 at 3 06 52 PM](https://user-images.githubusercontent.com/13590895/175649408-f86d7509-
413e-4690-b4d4-ce5240315a47.png)

**Comment by xinemata** [comment]
The top & bottom padding looks a little tall to my eyes. Would it be possible to bring them closer together? 

![image](https://user-images.githubusercontent.com/9159424/175787584-a69506cb-5451-462a-852a-4a54bb91fc88.png)

**Comment by Kcaden20** [comment]
Fixed
![Screen Shot 2022-06-27 at 11 51 06 AM](https://user-images.githubusercontent.com/13590895/175981512-04fe3ba4-a6c3-4bc8-b556-ea214aa4d9f8.png)

**Comment by xinemata** [comment]
Looking good. Closing the issue.
