### ISSUE TITLE
<hr> styling discrepancies across browsers and devices

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#22]
There appears to be three different look for the `<hr>`. 

On desktop / firefox, the line is decorated by two gray squares:

<img width="1167" alt="Screen Shot 2022-06-23 at 5 26 56 PM" src="https://user-images.githubusercontent.com/9159424/175431175-ddc35c37-6e80-4284-9a6e-3263abdc73e1.png">

On desktop / chrome, the line does not have decorations:

<img width="1192" alt="Screen Shot 2022-06-23 at 5 27 07 PM" src="https://user-images.githubusercontent.com/9159424/175431170-dd7e0f0b-a461-4cd3-938c-49c64a02806e.png">

On mobile / duckduckgo & safari, the line is decorated by two black squares:

![49b53ecc5e165ec662b10e089b7f4044950cff0f9005a451bba248b1d5da17a9](https://user-images.githubusercontent.com/9159424/175431477-d3870320-a408-4d6f-a9f0-59f9978d8cc0.png)

**Comment by Kcaden20** [comment]
This has been fixed and will be reflected in the next push which should be tomorrow. Each browser treats `::before` and `::after` differently so some extra lines of code needed to be added: 

- make the diamonds visible in Chrome/Brave
- Color them correctly in FF
