### ISSUE TITLE
half width <hr> under subpages

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#23]
Is it intentional for the `<hr>` between two subpages to be half-width?

<img width="1090" alt="Screen Shot 2022-06-23 at 5 44 08 PM" src="https://user-images.githubusercontent.com/9159424/175432573-3e389f34-5776-49e9-8650-a5fab25188f9.png">

Source: [Jingle Tales](https://criticalcode.recipes/contributions/jingle-tales)

**Comment by Kcaden20** [comment]
It was—as a way to create differentiation between different chapters of the contribution and all around different sections but seeing it in action, it actually doesn't look very good so I will remove.

**Comment by Kcaden20** [comment]
This has been removed, all `hrs` are the same length now.
