### ISSUE TITLE
ordered / unordered list line-height

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#25]
Not sure if this is just me, but I find the line-height above & under `<ol>` and `<ul>` to be off balance. Just wanted to point it out in case you didn't see them before. 

<img width="993" alt="Screen Shot 2022-06-24 at 9 06 31 AM" src="https://user-images.githubusercontent.com/9159424/175563748-4a007aa1-27dd-4442-a820-e1829e4b3fba.png">

**Comment by Kcaden20** [comment]
@xinemata  Can you link to this project?

**Comment by xinemata** [comment]
Yes! [It's here](https://criticalcode.recipes/contributions/esolangs-deprogramming-the-language-divide). Though I think this is consistent across all contribution pages.

**Comment by Kcaden20** [comment]
Thanks! The example was helpful. I've updated this. 
![Screen Shot 2022-06-24 at 1 28 18 PM](https://user-images.githubusercontent.com/13590895/175612160-f4f1ba4a-1460-4301-ad2b-e33e78ee1c4c.png)

**Comment by xinemata** [comment]
**Tested on macbook pro (2450 x 1600, chrome / firefox) and iphone 12 mini (duckduckgo):**

The update looks really nice on the devices / browsers I've tested with ✨
