### ISSUE TITLE
Make Dark Mode the Default

### ISSUE THREAD

**Issue by Kcaden20** [Kcaden20/critical-code-cookbook#27]
Dark mode should be the default theme. This includes switching the toggle button so Dark Mode is when the switch is 'on'

**Comment by Kcaden20** [comment]
@xinemata @munusshih I've decided that this isn't really a high enough priority or worth rewiring some of the logic and JS. If people really like the dark theme, they can just switch over to it. 

Let me know if this works with you and we can close the issue.

**Comment by xinemata** [comment]
I think that’s reasonable and works for me. 

>
