### ISSUE TITLE
Return symbol on iOS

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#28]
The return symbol appears as an emoji on iOS. Do we want to keep this? ![image](https://user-images.githubusercontent.com/9159424/175721650-d1d02735-0bf1-49cd-80aa-c68c384fa0bf.png)

**Comment by Kcaden20** [comment]
I’m indifferent! I don’t have an issue w it but maybe would be worth
looking into it to just keep it consistent.

**Comment by xinemata** [comment]
The emoji doesn't bother me too much too. Though I think I'm actually bothered by the hyperlink underline hidden behind the icons 😅 Maybe either use consistent symbol or pad the underline for mobile?

**Comment by Kcaden20** [comment]
@xinemata on mobile devices it's just going to get rid of the underline. 

Also I've made it so the footnotes `hr` and the `hr` between sections are the same length.

**Comment by xinemata** [comment]
All good now, closing the issue.
