### ISSUE TITLE
Change color 'white' to off-white

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#29]
The default white body texts feel a little harsh on my eyes when I read a longer entry such as [Towards a Reflexive Technoculture](https://criticalcode.recipes/contributions/towards-a-reflexive-technoculture). 

I'd suggest to change css variable `--colorWhite` and `body.dark-theme{ color: white;}` to`GhostWhite` or `WhiteSmoke` to subtly decrease the contrast.

**Comment by Kcaden20** [comment]
Color has been changed to `WhiteSmoke`
![Screen Shot 2022-06-27 at 10 49 42 AM](https://user-images.githubusercontent.com/13590895/175969571-3bb42935-ac56-4072-bc6c-bae4f71d73ee.png)

**Comment by xinemata** [comment]
Tested & closing the issue.
