### ISSUE TITLE
Acknowledge paragraph styling

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#3]
On iPhone 12 mini DuckDuckGo and safari, the "Acknowledgment" paragraph under The About page isn't contained within device width. 

![image](https://user-images.githubusercontent.com/9159424/174699309-6c204865-ea7a-4a86-b76d-efc94efccb77.png)

**Comment by Kcaden20** [comment]
With the latest size scaling for smaller devices, this has been fixed. 
![Screen Shot 2022-06-24 at 3 09 21 PM](https://user-images.githubusercontent.com/13590895/175649753-4d396da5-ea22-43c8-b877-42c57569d96b.png)

**Comment by xinemata** [comment]
Tested on iphone 12 mini and this appears to be working now! Closing the issue.
