### ISSUE TITLE
<code> font not loading properly on firefox

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#30]
The `<code>` font 'Inconsolata' appears to not load properly on firefox.  

Chrome:
<img width="537" alt="Screen Shot 2022-06-24 at 11 18 09 PM" src="https://user-images.githubusercontent.com/9159424/175759455-c000c54d-4d99-491c-8a08-fcdb6abeeffe.png">
Firefox:
<img width="469" alt="Screen Shot 2022-06-24 at 11 18 13 PM" src="https://user-images.githubusercontent.com/9159424/175759454-2fa960c8-4f69-4b3e-b65b-98d92d055dc6.png">

Source: https://criticalcode.recipes/contributions/annotating-a-feminist-internet-atfi

**Comment by Kcaden20** [comment]
@xinemata what version of FF are you using? It's loading on my local version and the online version for me. 
![Screen Shot 2022-06-27 at 11 02 41 AM](https://user-images.githubusercontent.com/13590895/175972306-0018e300-cd73-473a-a32a-779b3cfcad29.png)

<img width="1186" alt="Screen Shot 2022-06-27 at 11 02 48 AM" src="https://user-images.githubusercontent.com/13590895/175972280-43515b48-98ba-4212-b376-6c229e2a15cb.png">

**Comment by Kcaden20** [comment]
I've added a `monospace` font fallback just in case.

**Comment by xinemata** [comment]
Oh! I think this was caused by one of my privacy / ad-blocking tools installed on FF. It's a good idea to add `monospace` as fallback. I've just tested it again and works perfectly now. Closing the issue.
