### ISSUE TITLE
homepage section bg color in darkmode 

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#31]
I quite like the yellow/pink/purple bg that separates the section in the light mode:

<img width="382" alt="Screen Shot 2022-06-25 at 1 09 51 PM" src="https://user-images.githubusercontent.com/9159424/175787358-b99b3fed-b835-48a7-98cc-a5762df216de.png">

Since we're now using dark mode as the default, would it make sense to apply the same logic using three different darker shad colors from the design color palette? 

<img width="385" alt="Screen Shot 2022-06-25 at 1 10 04 PM" src="https://user-images.githubusercontent.com/9159424/175787360-3da093fb-ce14-4f0d-b35c-9f20d862cb21.png">

**Comment by Kcaden20** [comment]
Added
![Screen Shot 2022-06-27 at 10 18 38 AM](https://user-images.githubusercontent.com/13590895/175963275-12da3d43-de11-4c55-941b-3693a25669f1.png)

**Comment by xinemata** [comment]
This works! Thanks!!!
