### ISSUE TITLE
Resource page image border

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#32]
On resource page, the image borders are wider than the images. Would it be possible to either (1) reduce the extra paddings or (2) remove the borders?

<img width="1240" alt="Screen Shot 2022-06-25 at 1 29 56 PM" src="https://user-images.githubusercontent.com/9159424/175788020-31c09eb9-98a0-4715-a288-0cb397e05de5.png">

**Comment by Kcaden20** [comment]
Thumbnails have been set to cover all available space—would make sure future resources are in landscape so not too much of it gets cut off.
![Screen Shot 2022-06-27 at 10 54 15 AM](https://user-images.githubusercontent.com/13590895/175970565-67d34741-22c1-4cc8-a589-cf05bd71b4b6.png)

**Comment by xinemata** [comment]
That looks nice. Thank you. Would it be possible to give all the thumbnail content the same top-margins? The third thumbnail is just slightly higher than the first two in a way that feels slightly distracting to me. 

![175970565-67d34741-22c1-4cc8-a589-cf05bd71b4b6](https://user-images.githubusercontent.com/9159424/176008619-1f7aa09d-590d-47fb-bd76-1dbafabaf9de.png)

**Comment by Kcaden20** [comment]
ah, they were set to center but we can flush them along the top. 
![Screen Shot 2022-06-27 at 2 23 40 PM](https://user-images.githubusercontent.com/13590895/176009898-8bd060c6-7919-42b6-a8ab-035feeab6ab3.png)

**Comment by xinemata** [comment]
Yes! I think this looks better to me.

**Comment by Kcaden20** [comment]
Alright—will be in next push

**Comment by xinemata** [comment]
Problems stated have been solved. Closing the issue.
