### ISSUE TITLE
"About our work" missing a link

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#34]
The "About our work" section on the homepage is missing a link to the about page

<img width="809" alt="Screen Shot 2022-06-26 at 6 36 18 AM" src="https://user-images.githubusercontent.com/9159424/175814499-9ab57ee4-ad96-41b6-8e76-3c85c422dc3f.png">

**Comment by Kcaden20** [comment]
Added in
![Screen Shot 2022-06-27 at 10 16 13 AM](https://user-images.githubusercontent.com/13590895/175962773-37f8bc4a-931c-433b-ada7-8d32687a71a5.png)

**Comment by xinemata** [comment]
Looking good. Closing the issue!
