### ISSUE TITLE
Tiresias PC Font Bold not working

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#36]
The bolded version of `Tiresias PC Font` appears to be not working:

<img width="1180" alt="Screen Shot 2022-06-27 at 1 05 51 PM" src="https://user-images.githubusercontent.com/9159424/176016964-9260dd2e-e227-4077-b392-6aa823d187f4.png">

Editor view:
<img width="1163" alt="Screen Shot 2022-06-27 at 1 05 56 PM" src="https://user-images.githubusercontent.com/9159424/176016974-f9e154d2-9c1e-40de-b062-5c3c1f3e23dd.png">

Source: https://criticalcode.recipes/contributions/house-of-words

**Comment by Kcaden20** [comment]
So Tiresias Bold is working but it's super subtle. My solution is to use the heading font as a distinct bold state as it has a bold and bold italic state. See examples below. 
<img width="928" alt="Screen Shot 2022-06-27 at 5 51 33 PM" src="https://user-images.githubusercontent.com/13590895/176041957-010095cb-097b-44ae-8fc9-1f95f99dc2dc.png">
<img width="928" alt="Screen Shot 2022-06-27 at 5 51 24 PM" src="https://user-images.githubusercontent.com/13590895/176041958-e7907d36-21cf-4d4d-9f91-4ab8ce0362e7.png">

**Comment by xinemata** [comment]
Has this been implemented for mobile? Not seeeing it on my end yet. 

![image](https://user-images.githubusercontent.com/9159424/176057707-c3d27a03-c86d-4e93-8cac-c13cd5cdd639.png)

**Comment by Kcaden20** [comment]
@xinemata sorry, changes had not been pushed. 

It should show now on the website. Make sure to clear cache. 
<img width="1152" alt="Screen Shot 2022-06-28 at 11 20 45 PM" src="https://user-images.githubusercontent.com/13590895/176344180-883f592e-bb01-4a40-85b6-e8911a3656fd.png">

**Comment by xinemata** [comment]
Confirming that it's working now. Closing the issue.
