### ISSUE TITLE
pink overlay on image hover

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#37]
By the way! I remember seeing a faded pink overlay when the cursor hovers over images a short while ago and I don't see that anymore. Did you change your mind on it @Kcaden20?

**Comment by Kcaden20** [comment]
I'd been messing around with a hover style for the figures in general and wasn't happy with that specific one. I think I've settled on one that mimics the hyperlink style.
<img width="1115" alt="Screen Shot 2022-06-30 at 6 07 28 PM" src="https://user-images.githubusercontent.com/13590895/176786961-030ea245-0fd0-49c9-9b56-8c6f432ed5cf.png">
<img width="866" alt="Screen Shot 2022-06-30 at 6 07 36 PM" src="https://user-images.githubusercontent.com/13590895/176787023-79eb9a51-f294-4a7c-9884-a17efa2830aa.png">

**Comment by Kcaden20** [comment]
Nvm—Realized this doesn't work because images go to the corner.

**Comment by Kcaden20** [comment]
Images will just subtly fade out:
<img width="491" alt="Screen Shot 2022-06-30 at 6 16 22 PM" src="https://user-images.githubusercontent.com/13590895/176787930-61fb6c7e-2f08-4842-9887-9f94190342e7.png">
<img width="485" alt="Screen Shot 2022-06-30 at 6 16 15 PM" src="https://user-images.githubusercontent.com/13590895/176787933-d8d8f9f7-2115-4f4b-b349-9282aeeb3596.png">

**Comment by xinemata** [comment]
That looks good to me! Thanks for trying it out.

**Comment by xinemata** [comment]
Sorry I've just caught this now, but this is possibly not working with images that are set as "portrait" or "square". For example take a look at the Love Poem image on this entry: https://criticalcode.recipes/contributions/recipe-for-erotic-event-listeners

**Comment by Kcaden20** [comment]
@xinemata just tested—this is being caused by the alt-text. I just removed it and it worked properly. I've readded it for the time being though I'm unsure of how it's affecting it.

**Comment by xinemata** [comment]
This has been resolved. Closing the issue.
