### ISSUE TITLE
Styling for iPhone 12 mini

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#4]
A couple spacing issues were observed on iPhone 12 mini (DuckDuckGo and safari):

- the two toggle buttons in the menu bar & at the upper right corner seem vertically misaligned to me
- on homepage, the "Critical Coding Cookbook" bubble is covered by the top menu bar when visitors land on the homepage 
- on the contribution pages, when an ordered list is created, the text block expands fills up the entire device width. If there's a way to adjust the margin there that would be great 

![image](https://user-images.githubusercontent.com/9159424/174700539-98d684dc-51d0-4c5a-a1f7-7b234bb489f7.png)

![image](https://user-images.githubusercontent.com/9159424/174700552-5380d6c5-e73f-4d83-92cc-cdca6c493f4e.png)

**Comment by Kcaden20** [comment]
I don't have a mini to look at this on but these changes were made in responsive design mode and tested to `300px`. Documentation of the look on my end below. 

Please test when I push the latest changes. 
![Screen Shot 2022-06-24 at 3 11 11 PM](https://user-images.githubusercontent.com/13590895/175650072-57d50dea-46ce-4ffb-8403-f46e2d740b6f.png)
![Screen Shot 2022-06-24 at 3 11 04 PM](https://user-images.githubusercontent.com/13590895/175650074-c73d76e1-a170-4ed0-93d5-ebabba9f0e9e.png)

**Comment by xinemata** [comment]
Under [Joana and Renick's entry](https://criticalcode.recipes/contributions/choreographies-of-the-circle-other-geometries), the "steps" block isn't contained by device width for some reason. 

![image](https://user-images.githubusercontent.com/9159424/175814801-a707f21e-9752-4deb-9a60-f9a1a287a935.png)

**Comment by xinemata** [comment]
Consider making the call out boxes width flushes with paragraph width? 3 to 4 words per paragraph feels a little short to me. 

![image](https://user-images.githubusercontent.com/9159424/175815133-7b715a81-cc1e-4a7d-b29b-4943d706b7c3.png)

**Comment by xinemata** [comment]
Similar issue with [Noam's entry](https://criticalcode.recipes/contributions/the-gendered-cable-manifesto). The block quotes feel a little narrow

![image](https://user-images.githubusercontent.com/9159424/175815267-f92094f8-4093-45c8-9620-9037c16e164d.png)

**Comment by xinemata** [comment]
This image on [Noam's entry](https://criticalcode.recipes/contributions/the-gendered-cable-manifesto) isn't contained by device width for some reason. 

![image](https://user-images.githubusercontent.com/9159424/175815295-d492ff1f-c947-4f8c-8eed-540a2206e068.png)

**Comment by xinemata** [comment]
Is it possible to increase the size of the entry thumb titles? 

![image](https://user-images.githubusercontent.com/9159424/175815586-17ea23ec-7841-469d-8bd4-b556a6caba3f.png)

And maybe differentiate the sizes of h4 and h5 more for
legibility? 

![image](https://user-images.githubusercontent.com/9159424/175815659-3fd55270-110d-4559-a625-6de23a63f4e9.png)

Source: Kemi's entry

**Comment by Kcaden20** [comment]
Joanna and Renick’s was because the urls were really long. All URLS in a code block will now break to avoid this. 

Callouts and Blockquotes now go to the edge.

Can’t recreate the Noam issue. It is working on my phone and on the smallest responsive design phone size. 

I’ve increased the size of H4, H5 and generally the size of the text on mobile. I’m hesitant to change the size of the smaller sizes as it on a scale with the larger sizes, meaning I’ll have to size those up and it will cause the issues we were dealing with earlier.

**Comment by xinemata** [comment]
Callouts & blockquotes are looking great on my end! Joanna & Renick's entry is working too. 

You have somehow fixed Noam's image issue. And the thumbnail titles are looking much clearer now. I'd consider this closed.
