### ISSUE TITLE
footer link

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#40]
Sorry this is nitpicky, but can we only make "Join our Discord" a link?

<img width="700" alt="Screen Shot 2022-07-01 at 4 51 59 AM" src="https://user-images.githubusercontent.com/9159424/176814041-72df78ae-74e0-420d-bc52-c82aad5dd3d6.png">

**Comment by Kcaden20** [comment]
So the social links make the entire phrase a link. If you only need a part of it to be a link—I'd say to use the other text section below the social media stuff.
![Screen Shot 2022-06-30 at 11 34 37 PM](https://user-images.githubusercontent.com/13590895/176818472-36aea172-ca50-4456-8ea8-8a463e21be9d.png)

**Comment by xinemata** [comment]
This is working well now. Closing the issue.
