### ISSUE TITLE
Footer section visual separation

### ISSUE THREAD

**Issue by xinemata** [Kcaden20/critical-code-cookbook#41]
It seems to me that since there is a visual separation on the hompage for the footer (in both light / dark mode), same thing would happen on Contributions / Resources / About / Accessibility / Downloads pages.

<img width="1108" alt="Screen Shot 2022-07-01 at 4 54 10 AM" src="https://user-images.githubusercontent.com/9159424/176814348-e41c2ca7-e9d7-4d61-9346-0c1ef25724b5.png">
<img width="1107" alt="Screen Shot 2022-07-01 at 4 53 52 AM" src="https://user-images.githubusercontent.com/9159424/176814350-62ac7cd6-8919-4301-a147-892590d8036b.png">

**Comment by Kcaden20** [comment]
![Screen Shot 2022-06-30 at 11 34 37 PM](https://user-images.githubusercontent.com/13590895/176818408-8af72c7d-412e-41bb-be85-9457e7d7f325.png)

**Comment by xinemata** [comment]
this has been resolved. closing.
